version: "3.8"
services:
  mysqldb:
#    official docker image
    image: mysql:5.7
#    restart policy
    restart: unless-stopped
#    specify .env path
    env_file: ./.env
#    provide setting using environment variables
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#      map volumes folder
    volumes:
      - db:/var/lib/mysql
  app:
#    dependency order mysql starts before the app
    depends_on:
      - mysqldb
#      configuration options that are applied at build time that we defined in the Dockerfile with relative path
    build: ./MovieRental
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#     environmental variables that Spring Boot application uses
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
#      keep open the terminal after building container
    stdin_open: true
    tty: true
volumes:
  db: