version: "3"
services:
  server:
    image: movierental
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/movierental?useSSL=false
    networks:
      - movierental-mysql
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    networks:
      - movierental-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=QWer12
      - MYSQL_DATABASE=movierental
      - MYSQL_USER=staff
      - MYSQL_PASSWORD=1234

networks:
  movierental-mysql: